### ISSUE TITLE
Errors in iOS 9 pod installation

### ISSUE THREAD

**Issue by fareskalaboud** [haaakon/SingleLineKeyboardResize#6]
![image](https://cloud.githubusercontent.com/assets/4170046/13574397/d51fe506-e47b-11e5-8082-328963b8c1ce.png)

Respectively:

Line 30
Line 38
Line 40
Line 54
Line 56

**Comment by fareskalaboud** [comment]
![image](https://cloud.githubusercontent.com/assets/4170046/13574395/d09c196e-e47b-11e5-9dc3-453d2f2eb09b.png)

**Comment by mrfarukturgut** [comment]
I have got it too.

**Comment by mrfarukturgut** [comment]
fareskalaboud, I figured out a way. Go in `UIViewControllers+Keyboard.swift` file and copy paste all of it. Then simply paste it to simple swift file. It worked for me.

**Comment by mrfarukturgut** [comment]
For the developer, it works with collectionView as well.

**Comment by haaakon** [comment]
Should be fixed  as of now
