### ISSUE TITLE
Some error calculating keyboard size for bigger phones (as example iPhone 6)

### ISSUE THREAD

**Issue by vronin** [haaakon/SingleLineKeyboardResize#7]
It works very well for iPhone 5 on which I mainly played with it.
However, it has problems with resizing on iPhone 6.

As example, I have a view with just one TextView which occupies whole screen. The keyboard is opened when TextView becomes a first responder. SingleLineKeyboardResize is executed and it inserts to TextView. However, inserts are a little bit wrong size. As result, the bottom of TextView will end up being under the keyboard.

**Comment by haaakon** [comment]
Hmm. Will investiage

**Comment by klwoon** [comment]
I believe I have the same problem on UITableView too, on iphone 6 the bottom 2 rows will be covered by keyboard. However if the keyboard is dismissed and showed again, the tableView will be resized correctly.

**Comment by haaakon** [comment]
You can consistently replicate this?

**Comment by klwoon** [comment]
Yes

**Comment by klwoon** [comment]
It worked if the listener changed from `UIKeyboardWillShowNotification` to `UIKeyboardDidShowNotification`

**Comment by vronin** [comment]
I was doing becomeFirstResponder() at viewDidLoad. SingleLineKeyboardResize was getting called very early when frames weren't set correctly yet. I moved becomeFirstResponder() to viewWillAppear and it solved this problem
